import type { Metadata } from "next";
import "./globals.css";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import AuthenticatedTopNav from "@/app/components/authenticated-top-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className="antialiased">
        {user ? <AuthenticatedTopNav /> : null}
        {children}
      </body>
    </html>
  );
}
